name: "yolo11n_onnx"
platform: "onnxruntime_onnx"
max_batch_size: 2
default_model_filename: "model.onnx"
version_policy {
  specific {
    versions: 1
  }
}
dynamic_batching {
  preferred_batch_size: 2
  max_queue_delay_microseconds: 5000
}
input [
  {
    name: "images"
    data_type: TYPE_FP32
    dims: [ 3, 640, 640 ]
  }
]
output [
  {
    name: "output0"
    data_type: TYPE_FP32
    dims: [ 84, 8400 ]
  }
]
