name: "resnet50_tensorrt"
platform: "tensorrt_plan"
max_batch_size: 8
default_model_filename: "model.plan"
version_policy {
  specific {
    versions: 1
  }
}
dynamic_batching {
  preferred_batch_size: 4
  preferred_batch_size: 8
  max_queue_delay_microseconds: 5000
}
input [
  {
    name: "images"
    data_type: TYPE_FP32
    dims: [ 3, 224, 224 ]
  }
]
output [
  {
    name: "logits"
    data_type: TYPE_FP32
    dims: [ 1000 ]
    label_filename: "imagenet1k.txt"
  }
]
